apiVersion: apps/v1
kind: Deployment
metadata:
  name: composeexample-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: composeexample
  template:
    metadata:
      labels:
        app: composeexample
    spec:
      containers:
      - name: composeexample-container
        image: composeexample:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
